name = "mastra-cloudflare-workflows-example"
main = "src/worker.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[workflows]]
name = "mastra-workflow"
binding = "MASTRA_WORKFLOW"
class_name = "MastraCloudflareWorkflow"
