name = "mastra-cloudflare-workflows-types"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# This is just for generating types - not for deployment
# Users will have their own wrangler.toml in their projects

[[workflows]]
name = "example-workflow"
binding = "EXAMPLE_WORKFLOW"
class_name = "ExampleWorkflow"
